name: Website build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      commit_message: ${{ github.event.head_commit.message }}
    steps:
    - name: Checkout active branch
      uses: actions/checkout@v2
      with:
        path: 'work'
    - name: Prepare the web pages with Pandoc
      run: |
        # Package installation is only needed for local testing.
        #echo "Updating repositories..."
        #apt-get -qq update
        #echo "Repositories updated."
        #echo "Installing necessary dependencies..."
        #apt-get -qq install make docker.io -y
        #echo "Dependencies installed."
        # The actual build begins here.
        cd work
        mkdir tmp
        make build
    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref : 'gh-pages'
        path: 'gh-pages'
    - name: Copy site to gh-pages branch
      run: |
        rsync -mrtu \
          ${{ github.workspace }}/work/  ${{ github.workspace }}/gh-pages/ \
          --delete --exclude spec --exclude lib --exclude *.bib
        mv -f ${{ github.workspace }}/gh-pages/tmp/* ${{ github.workspace }}/gh-pages/
    - name: Test Jekyll site build
      run: |
        docker run -v ${{ github.workspace }}/gh-pages:/srv/jekyll \
          jekyll/jekyll:3.8.5 /bin/bash -c "chmod 777 /srv/jekyll && jekyll build"
    - name: Commit changes to gh-pages branch
      run: |
        cd ${{ github.workspace }}/gh-pages
        git config --local user.email "runner@github.com"
        git config --local user.name  "Automated build"
        git config --local advice.addIgnoredFile false
        git add *
        git commit -m "${{ env.commit_message }}" -a
    - name: Push changes to origin
      uses: ad-m/github-push-action@master
      with:
        branch: 'gh-pages'
        directory: 'gh-pages'
        github_token: ${{ secrets.GITHUB_TOKEN }}
