name: Jekyll site CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: 'work'
    - name: Prepare the web pages with Pandoc
      run: |
        # Package installation is only needed for local testing.
        echo "Updating repositories..."
        apt-get -qq update
        echo "Repositories updated."
        echo "Installing necessary dependencies..."
        apt-get -qq install make docker.io -y
        echo "Dependencies installed."
        # The actual build begins here.
        make build
    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        ref : 'gh-pages'
        path: 'gh-pages'
    - name: Copy site to gh-pages branch
      run: |
        cp -f  ${{ github.workspace }}/work/_config.yml  ${{ github.workspace }}/gh-pages/_config.yml
        cp -f  ${{ github.workspace }}/work/Gemfile      ${{ github.workspace }}/gh-pages/Gemfile
        cp -f  ${{ github.workspace }}/work/Gemfile.lock ${{ github.workspace }}/gh-pages/Gemfile.lock
        cp -rf ${{ github.workspace }}/work/assets       ${{ github.workspace }}/gh-pages/assets
        cp -rf ${{ github.workspace }}/work/tmp/*        ${{ github.workspace }}/gh-pages/
    - name: Test Jekyll site build
      uses: docker://jekyll/jekyll:3.8.5
      with:
        args: "jekyll build"
